### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by hctrbz** [awesomemotive/WP-Mail-SMTP#51] opened 2019-04-26 18:07 UTC
## Plugin version 
Version 1.4.2
## Current Behavior

Everything seems to work but when I submit something like add a new user to change their role I see this error on a white page.

Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /home/mahogan9/public_html/agronosotros.com/wp-content/plugins/wp-mail-smtp/src/Providers/OptionsAbstract.php on line 3

If this is something simple to fix, my apologies. I am not very versed in this.

## Expected Behavior

I don't think this should be happening

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by slaFFik** [comment] 2019-04-29 10:56
1. Remove the current plugin `wp-mail-smtp` that you have installed
1. Reupload the plugin from scratch, install it through WordPress Plugins interface
1. Check again.

I think the plugin files were altered (edited) by someone or something, which is not good.

**Comment by slaFFik** [comment] 2019-05-03 13:48
Closing as there were no reply and the issue is definitely (imo) not in the plugin code.
Feel free to reply and the issue persists.

**Closed as completed by slaFFik** 2019-05-03 13:48 UTC
