### ISSUE TITLE
Error never disappears

### ISSUE THREAD

**Issue by simonsutcliffe** [awesomemotive/WP-Mail-SMTP#13] opened 2018-06-29 07:43 UTC
## Plugin version 
1.3.0

## Current Behavior
There appears to have been a moment when the plugin could not send mail to the SMTP server.  I have checked the settings and ran a test,  Both are OK.  I received the message as expected.

## Expected Behavior
After doing a successful test I would expect the message to disappear.

## Screenshots (if appropriate)

![2018-06-29 08_41_46-wp mail smtp options sutcliffe photography wordpress](https://user-images.githubusercontent.com/40686785/42079747-673c91a6-7b78-11e8-9cd6-94aaad0f3daf.png)

**Comment by slaFFik** [comment] 2018-06-29 09:13
Thanks for the report.

Working on it, if confirmed - should be fixed in 1.3.1 due today.

**Closed as completed by slaFFik** 2018-06-29 09:13 UTC
