### ISSUE TITLE
"a critical error has occurred" in wp-admin

### ISSUE THREAD

**Issue by gastornov** [awesomemotive/WP-Mail-SMTP#87] opened 2020-11-18 11:32 UTC
## Current Behavior
When the pro version is activated from wp-admin, the basic version is deactivated automatically. 
But - when plugins are activated ”in bulk”, both plugins get activated, causing wp-admin to be blocked by "a critical error has occurred" 

## Steps to Reproduce

1. rename plugin folder to "plugins_old" via ftp
2. create folder "plugins" via ftp
3. delete or rename folder "plugins"
4. rename folder "plugins_old" to "plugins"
5. go to wp-admin > addons, tick all plugins, choose "activate all"
6. wait for error message
![Namnlös](https://user-images.githubusercontent.com/74657431/99525175-c19da000-2999-11eb-840d-55cad6f08869.png)

**Comment by capuderg** [comment] 2020-11-19 06:00
Hi @gastornov 

thank you for reporting this issue!

We'll take a look and try to fix this issue for the next plugin update.

Have a nice day!

**Comment by capuderg** [comment] 2020-12-24 06:58
Hi @gastornov,

could you please let me know which mailer you were using when you bulk activated both Lite and Pro versions of the plugin? Did you by any chance use one of the Pro mailers?

We've tried to reproduce this issue, but could not.

I think the actual critical error in your case was caused by a bug in our plugin, where if you used a PRO-only mailer (configured in the Pro plugin) and then activated the Lite plugin version it would throw a PHP fatal error. This bug will be fixed in the next major plugin update.

As for the bulk plugin activation - it does not cause any issues on its own as far as we tested it.

Thank you again for reporting this issue and have a nice day!

**Closed as completed by capuderg** 2020-12-24 06:58 UTC
Labels: bug

**Comment by gastornov** [comment] 2021-01-11 07:38
Hi, sorry for the late response; yes, I use Office 365 mailer.

**Comment by capuderg** [comment] 2021-01-11 08:12
Hi @gastornov,

thanks for letting us know. So the issue is indeed like explained in my previous message. It will be fixed in the next plugin update.

Have a nice day!
