### ISSUE TITLE
Mailgun - Mail formatting breaks to one line.

### ISSUE THREAD

**Issue by Webtica** [awesomemotive/WP-Mail-SMTP#3] opened 2018-06-12 17:25 UTC
## Plugin version 
1.2.5
## Current Behavior
When sending mail with Mailgun everything gets broken to one line and loses formatting.

## Expected Behavior
Send correctly

## Steps to Reproduce (for bugs)
1. Setup Mailgun
2. Send mail via any plugin.

**Comment by slaFFik** [comment] 2018-06-12 21:27
Hi @Webtica, 

Thanks for reporting this issue! It's a known one, so I'm closing as a duplicate of our internal issue.
This will be fixed in the upcoming 1.3.

**Closed as completed by slaFFik** 2018-06-12 21:27 UTC
